<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


/**
 * AllworkbooksAllworkbookslive - OK
 * 
 * @package taamai\taamai\Models\Operations
 * @access public
 */
class AllworkbooksAllworkbookslive
{
	#[\JMS\Serializer\Annotation\SerializedName('code')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $code;
    
    /**
     * $data
     * 
     * @var array<\taamai\taamai\Models\Shared\Datum1> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<taamai\taamai\Models\Shared\Datum1>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('mesaage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $mesaage;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	public function __construct()
	{
		$this->code = 0;
		$this->data = [];
		$this->mesaage = "";
		$this->status = "";
	}
}
