<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class CreateProductRequestBody
{
	#[SpeakeasyMetadata('form:name=bullet_points')]
    public string $bulletPoints;
    
	#[SpeakeasyMetadata('form:name=description')]
    public string $description;
    
	#[SpeakeasyMetadata('form:name=name')]
    public string $name;
    
	#[SpeakeasyMetadata('form:name=tags[0]')]
    public string $tags0;
    
	#[SpeakeasyMetadata('form:name=tags[1]')]
    public string $tags1;
    
	#[SpeakeasyMetadata('form:name=target_audience')]
    public string $targetAudience;
    
	#[SpeakeasyMetadata('form:name=user_id')]
    public int $userId;
    
	public function __construct()
	{
		$this->bulletPoints = "";
		$this->description = "";
		$this->name = "";
		$this->tags0 = "";
		$this->tags1 = "";
		$this->targetAudience = "";
		$this->userId = 0;
	}
}
