<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


class Data17
{
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('expires_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $expiresAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('image')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $image;
    
	#[\JMS\Serializer\Annotation\SerializedName('image_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $imageName;
    
	#[\JMS\Serializer\Annotation\SerializedName('image_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $imageUrl;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('plan_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $planType;
    
	#[\JMS\Serializer\Annotation\SerializedName('resolution')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $resolution;
    
	#[\JMS\Serializer\Annotation\SerializedName('storage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $storage;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $userId;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_folder_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workbookFolderId;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workbookId;
    
	public function __construct()
	{
		$this->createdAt = "";
		$this->description = "";
		$this->expiresAt = "";
		$this->id = 0;
		$this->image = "";
		$this->imageName = "";
		$this->imageUrl = "";
		$this->name = "";
		$this->planType = "";
		$this->resolution = "";
		$this->storage = "";
		$this->updatedAt = "";
		$this->userId = 0;
		$this->workbookFolderId = "";
		$this->workbookId = "";
	}
}
