<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class FileuploadRequestBody
{
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public FileuploadRequestBodyFile $file;
    
	public function __construct()
	{
		$this->file = new \taamai\taamai\Models\Operations\FileuploadRequestBodyFile();
	}
}
