<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


/**
 * GenerateCodeGenerateCode - OK
 * 
 * @package taamai\taamai\Models\Operations
 * @access public
 */
class GenerateCodeGenerateCode
{
	#[\JMS\Serializer\Annotation\SerializedName('current')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $current;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('old')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $old;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $text;
    
	public function __construct()
	{
		$this->current = 0;
		$this->id = 0;
		$this->old = "";
		$this->status = "";
		$this->text = "";
	}
}
