<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class GeneratespeechtotextRequestBody
{
	#[SpeakeasyMetadata('multipartForm:file=true')]
    public GeneratespeechtotextRequestBodyAudioFile $audioFile;
    
	#[SpeakeasyMetadata('multipartForm:name=document')]
    public string $document;
    
	#[SpeakeasyMetadata('multipartForm:name=language')]
    public string $language;
    
	#[SpeakeasyMetadata('multipartForm:name=task')]
    public string $task;
    
	#[SpeakeasyMetadata('multipartForm:name=user_id')]
    public int $userId;
    
	#[SpeakeasyMetadata('multipartForm:name=workbook_folder_id')]
    public int $workbookFolderId;
    
	#[SpeakeasyMetadata('multipartForm:name=workbook_id')]
    public int $workbookId;
    
	public function __construct()
	{
		$this->audioFile = new \taamai\taamai\Models\Operations\GeneratespeechtotextRequestBodyAudioFile();
		$this->document = "";
		$this->language = "";
		$this->task = "";
		$this->userId = 0;
		$this->workbookFolderId = 0;
		$this->workbookId = 0;
	}
}
