<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class GenerateCodeRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=document')]
    public string $document;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=instructions')]
    public string $instructions;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=language')]
    public string $language;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public int $userId;
    
	public function __construct()
	{
		$this->document = "";
		$this->instructions = "";
		$this->language = "";
		$this->userId = 0;
	}
}
