<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class GeneratespeechtotextRequestBodyAudioFile
{
	#[SpeakeasyMetadata('multipartForm:name=audio_file')]
    public string $audioFile;
    
	#[SpeakeasyMetadata('multipartForm:content=true')]
    public string $content;
    
	public function __construct()
	{
		$this->audioFile = "";
		$this->content = "";
	}
}
