<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class GenerateimagefromAIRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=max_results')]
    public int $maxResults;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=name')]
    public string $name;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=resolution')]
    public string $resolution;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=title')]
    public string $title;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public int $userId;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workbook_folder_id')]
    public int $workbookFolderId;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workbook_id')]
    public int $workbookId;
    
	public function __construct()
	{
		$this->maxResults = 0;
		$this->name = "";
		$this->resolution = "";
		$this->title = "";
		$this->userId = 0;
		$this->workbookFolderId = 0;
		$this->workbookId = 0;
	}
}
