<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


/**
 * GenerateimagefromAIGenerateimagefromAI - OK
 * 
 * @package taamai\taamai\Models\Operations
 * @access public
 */
class GenerateimagefromAIGenerateimagefromAI
{
	#[\JMS\Serializer\Annotation\SerializedName('current')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $current;
    
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('taamai\taamai\Models\Operations\GenerateimagefromAIGenerateimagefromAIData17')]
    public GenerateimagefromAIGenerateimagefromAIData17 $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('old')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $old;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	public function __construct()
	{
		$this->current = 0;
		$this->data = new \taamai\taamai\Models\Operations\GenerateimagefromAIGenerateimagefromAIData17();
		$this->old = "";
		$this->status = "";
	}
}
