<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class LoginRequestBody
{
	#[SpeakeasyMetadata('form:name=email')]
    public string $email;
    
	#[SpeakeasyMetadata('form:name=password')]
    public string $password;
    
	public function __construct()
	{
		$this->email = "";
		$this->password = "";
	}
}
