<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class NewRequestRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=path')]
    public string $path;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=question')]
    public string $question;
    
	public function __construct()
	{
		$this->path = "";
		$this->question = "";
	}
}
