<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class PromptTemplatesRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cat')]
    public string $cat;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sub_cat')]
    public string $subCat;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public int $userId;
    
	public function __construct()
	{
		$this->cat = "";
		$this->subCat = "";
		$this->userId = 0;
	}
}
