<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


/**
 * RegisterExamplewithdefaultplansubdomainandsubsctpion - OK
 * 
 * @package taamai\taamai\Models\Operations
 * @access public
 */
class RegisterExamplewithdefaultplansubdomainandsubsctpion
{
	#[\JMS\Serializer\Annotation\SerializedName('access_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $accessToken;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	#[\JMS\Serializer\Annotation\SerializedName('result')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    public bool $result;
    
	#[\JMS\Serializer\Annotation\SerializedName('user')]
    #[\JMS\Serializer\Annotation\Type('taamai\taamai\Models\Operations\User2')]
    public User2 $user;
    
	public function __construct()
	{
		$this->accessToken = "";
		$this->message = "";
		$this->result = false;
		$this->user = new \taamai\taamai\Models\Operations\User2();
	}
}
