<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class RegisterRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=country')]
    public string $country;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=email')]
    public string $email;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=name')]
    public string $name;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=password')]
    public string $password;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=subdomain')]
    public string $subdomain;
    
	public function __construct()
	{
		$this->country = "";
		$this->email = "";
		$this->name = "";
		$this->password = "";
		$this->subdomain = "";
	}
}
