<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class SavetranscriptRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=text')]
    public string $text;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=title')]
    public string $title;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=transcript_id')]
    public int $transcriptId;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public int $userId;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workbook_folder_id')]
    public int $workbookFolderId;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workbook_id')]
    public int $workbookId;
    
	public function __construct()
	{
		$this->text = "";
		$this->title = "";
		$this->transcriptId = 0;
		$this->userId = 0;
		$this->workbookFolderId = 0;
		$this->workbookId = 0;
	}
}
