<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;

use \taamai\taamai\Utils\SpeakeasyMetadata;
class UpdateProductRequest
{
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=bullet_points')]
    public int $bulletPoints;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=description')]
    public string $description;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=name')]
    public string $name;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=product_id')]
    public int $productId;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tags[0]')]
    public string $tags0;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=target_audience')]
    public string $targetAudience;
    
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=user_id')]
    public int $userId;
    
	public function __construct()
	{
		$this->bulletPoints = 0;
		$this->description = "";
		$this->name = "";
		$this->productId = 0;
		$this->tags0 = "";
		$this->targetAudience = "";
		$this->userId = 0;
	}
}
