<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


class User
{
	#[\JMS\Serializer\Annotation\SerializedName('address')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $address;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_chars')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $availableChars;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_chars_prepaid')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $availableCharsPrepaid;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_images')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $availableImages;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_images_prepaid')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $availableImagesPrepaid;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_minutes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $availableMinutes;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_minutes_prepaid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $availableMinutesPrepaid;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_words')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $availableWords;
    
	#[\JMS\Serializer\Annotation\SerializedName('available_words_prepaid')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $availableWordsPrepaid;
    
	#[\JMS\Serializer\Annotation\SerializedName('balance')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $balance;
    
	#[\JMS\Serializer\Annotation\SerializedName('city')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $city;
    
	#[\JMS\Serializer\Annotation\SerializedName('ckbox')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $ckbox;
    
	#[\JMS\Serializer\Annotation\SerializedName('company')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $company;
    
	#[\JMS\Serializer\Annotation\SerializedName('country')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $country;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('default_temp_language')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $defaultTempLanguage;
    
	#[\JMS\Serializer\Annotation\SerializedName('default_tone')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultTone;
    
	#[\JMS\Serializer\Annotation\SerializedName('default_voiceover_language')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultVoiceoverLanguage;
    
	#[\JMS\Serializer\Annotation\SerializedName('default_voiceover_voice')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $defaultVoiceoverVoice;
    
	#[\JMS\Serializer\Annotation\SerializedName('email')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $email;
    
	#[\JMS\Serializer\Annotation\SerializedName('email_verified_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $emailVerifiedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('google2fa_enabled')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $google2faEnabled;
    
	#[\JMS\Serializer\Annotation\SerializedName('google2fa_secret')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $google2faSecret;
    
	#[\JMS\Serializer\Annotation\SerializedName('group')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $group;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('job_role')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $jobRole;
    
	#[\JMS\Serializer\Annotation\SerializedName('last_seen')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lastSeen;
    
	#[\JMS\Serializer\Annotation\SerializedName('member_role')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $memberRole;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('oauth_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $oauthId;
    
	#[\JMS\Serializer\Annotation\SerializedName('oauth_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $oauthType;
    
	#[\JMS\Serializer\Annotation\SerializedName('parent_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $parentId;
    
	#[\JMS\Serializer\Annotation\SerializedName('phone_number')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $phoneNumber;
    
	#[\JMS\Serializer\Annotation\SerializedName('plan_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $planId;
    
	#[\JMS\Serializer\Annotation\SerializedName('plan_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $planType;
    
	#[\JMS\Serializer\Annotation\SerializedName('postal_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $postalCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('product_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $productId;
    
	#[\JMS\Serializer\Annotation\SerializedName('profile_photo_path')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $profilePhotoPath;
    
	#[\JMS\Serializer\Annotation\SerializedName('referral_bank_requisites')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $referralBankRequisites;
    
	#[\JMS\Serializer\Annotation\SerializedName('referral_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $referralId;
    
	#[\JMS\Serializer\Annotation\SerializedName('referral_payment_method')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $referralPaymentMethod;
    
	#[\JMS\Serializer\Annotation\SerializedName('referral_paypal')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $referralPaypal;
    
	#[\JMS\Serializer\Annotation\SerializedName('referred_by')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $referredBy;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('subdomain')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $subdomain;
    
	#[\JMS\Serializer\Annotation\SerializedName('subdomain_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $subdomainToken;
    
	#[\JMS\Serializer\Annotation\SerializedName('total_chars')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalChars;
    
	#[\JMS\Serializer\Annotation\SerializedName('total_images')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalImages;
    
	#[\JMS\Serializer\Annotation\SerializedName('total_minutes')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $totalMinutes;
    
	#[\JMS\Serializer\Annotation\SerializedName('total_words')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $totalWords;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('website')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $website;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workbook;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_folder_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $workbookFolderId;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $workbookId;
    
	public function __construct()
	{
		$this->address = "";
		$this->availableChars = 0;
		$this->availableCharsPrepaid = 0;
		$this->availableImages = 0;
		$this->availableImagesPrepaid = 0;
		$this->availableMinutes = "";
		$this->availableMinutesPrepaid = "";
		$this->availableWords = 0;
		$this->availableWordsPrepaid = 0;
		$this->balance = 0;
		$this->city = "";
		$this->ckbox = "";
		$this->company = "";
		$this->country = "";
		$this->createdAt = "";
		$this->defaultTempLanguage = 0;
		$this->defaultTone = "";
		$this->defaultVoiceoverLanguage = "";
		$this->defaultVoiceoverVoice = "";
		$this->email = "";
		$this->emailVerifiedAt = "";
		$this->google2faEnabled = 0;
		$this->google2faSecret = "";
		$this->group = "";
		$this->id = 0;
		$this->jobRole = "";
		$this->lastSeen = "";
		$this->memberRole = 0;
		$this->name = "";
		$this->oauthId = "";
		$this->oauthType = "";
		$this->parentId = 0;
		$this->phoneNumber = "";
		$this->planId = 0;
		$this->planType = "";
		$this->postalCode = "";
		$this->productId = 0;
		$this->profilePhotoPath = "";
		$this->referralBankRequisites = "";
		$this->referralId = "";
		$this->referralPaymentMethod = "";
		$this->referralPaypal = "";
		$this->referredBy = "";
		$this->status = "";
		$this->subdomain = "";
		$this->subdomainToken = "";
		$this->totalChars = 0;
		$this->totalImages = 0;
		$this->totalMinutes = "";
		$this->totalWords = 0;
		$this->updatedAt = "";
		$this->website = "";
		$this->workbook = "";
		$this->workbookFolderId = 0;
		$this->workbookId = 0;
	}
}
