<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Operations;


/**
 * WorkbookvoiceoversWorkbookvoiceovers - OK
 * 
 * @package taamai\taamai\Models\Operations
 * @access public
 */
class WorkbookvoiceoversWorkbookvoiceovers
{
	#[\JMS\Serializer\Annotation\SerializedName('count')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $count;
    
    /**
     * $data
     * 
     * @var array<\taamai\taamai\Models\Shared\Data6> $data
     */
	#[\JMS\Serializer\Annotation\SerializedName('data')]
    #[\JMS\Serializer\Annotation\Type('array<taamai\taamai\Models\Shared\Data6>')]
    public array $data;
    
	#[\JMS\Serializer\Annotation\SerializedName('message')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $message;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $status;
    
	public function __construct()
	{
		$this->count = 0;
		$this->data = [];
		$this->message = "";
		$this->status = "";
	}
}
