<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Data11
{
	#[\JMS\Serializer\Annotation\SerializedName('active')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $active;
    
	#[\JMS\Serializer\Annotation\SerializedName('ai')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $ai;
    
	#[\JMS\Serializer\Annotation\SerializedName('ai_done')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $aiDone;
    
	#[\JMS\Serializer\Annotation\SerializedName('ai_used_tokens')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $aiUsedTokens;
    
	#[\JMS\Serializer\Annotation\SerializedName('alias')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $alias;
    
	#[\JMS\Serializer\Annotation\SerializedName('content')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $content;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deletedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('lang')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lang;
    
	#[\JMS\Serializer\Annotation\SerializedName('md')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $md;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('paid')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $paid;
    
	#[\JMS\Serializer\Annotation\SerializedName('price')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $price;
    
	#[\JMS\Serializer\Annotation\SerializedName('response')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $response;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $type;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $userId;
    
	public function __construct()
	{
		$this->active = 0;
		$this->ai = 0;
		$this->aiDone = 0;
		$this->aiUsedTokens = 0;
		$this->alias = "";
		$this->content = "";
		$this->createdAt = "";
		$this->deletedAt = "";
		$this->id = 0;
		$this->lang = "";
		$this->md = "";
		$this->name = "";
		$this->paid = 0;
		$this->price = 0;
		$this->response = "";
		$this->type = "";
		$this->updatedAt = "";
		$this->userId = 0;
	}
}
