<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Data6
{
	#[\JMS\Serializer\Annotation\SerializedName('audio_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $audioType;
    
	#[\JMS\Serializer\Annotation\SerializedName('characters')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $characters;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deletedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('expires_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $expiresAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('file_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $fileName;
    
	#[\JMS\Serializer\Annotation\SerializedName('gender')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $gender;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('language')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $language;
    
	#[\JMS\Serializer\Annotation\SerializedName('language_flag')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $languageFlag;
    
	#[\JMS\Serializer\Annotation\SerializedName('mode')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $mode;
    
	#[\JMS\Serializer\Annotation\SerializedName('plan_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $planType;
    
	#[\JMS\Serializer\Annotation\SerializedName('project')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $project;
    
	#[\JMS\Serializer\Annotation\SerializedName('result_ext')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $resultExt;
    
	#[\JMS\Serializer\Annotation\SerializedName('result_url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $resultUrl;
    
	#[\JMS\Serializer\Annotation\SerializedName('storage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $storage;
    
	#[\JMS\Serializer\Annotation\SerializedName('text')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $text;
    
	#[\JMS\Serializer\Annotation\SerializedName('text_raw')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $textRaw;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $title;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $userId;
    
	#[\JMS\Serializer\Annotation\SerializedName('vendor')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $vendor;
    
	#[\JMS\Serializer\Annotation\SerializedName('vendor_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $vendorId;
    
	#[\JMS\Serializer\Annotation\SerializedName('voice')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $voice;
    
	#[\JMS\Serializer\Annotation\SerializedName('voice_id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $voiceId;
    
	#[\JMS\Serializer\Annotation\SerializedName('voice_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $voiceType;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_folder_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $workbookFolderId;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $workbookId;
    
	public function __construct()
	{
		$this->audioType = "";
		$this->characters = 0;
		$this->createdAt = "";
		$this->deletedAt = "";
		$this->expiresAt = "";
		$this->fileName = "";
		$this->gender = "";
		$this->id = 0;
		$this->language = "";
		$this->languageFlag = "";
		$this->mode = "";
		$this->planType = "";
		$this->project = "";
		$this->resultExt = "";
		$this->resultUrl = "";
		$this->storage = "";
		$this->text = "";
		$this->textRaw = "";
		$this->title = "";
		$this->updatedAt = "";
		$this->userId = 0;
		$this->vendor = "";
		$this->vendorId = "";
		$this->voice = "";
		$this->voiceId = "";
		$this->voiceType = "";
		$this->workbookFolderId = 0;
		$this->workbookId = 0;
	}
}
