<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Data16
{
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deletedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('edit')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $edit;
    
    /**
     * $fields
     * 
     * @var array<string> $fields
     */
	#[\JMS\Serializer\Annotation\SerializedName('fields')]
    #[\JMS\Serializer\Annotation\Type('array<string>')]
    public array $fields;
    
	#[\JMS\Serializer\Annotation\SerializedName('group')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $group;
    
	#[\JMS\Serializer\Annotation\SerializedName('icon')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $icon;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('image')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $image;
    
	#[\JMS\Serializer\Annotation\SerializedName('lang')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $lang;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('new')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $new;
    
	#[\JMS\Serializer\Annotation\SerializedName('package')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $package;
    
	#[\JMS\Serializer\Annotation\SerializedName('professional')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $professional;
    
	#[\JMS\Serializer\Annotation\SerializedName('prompt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $prompt;
    
	#[\JMS\Serializer\Annotation\SerializedName('public')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $public;
    
	#[\JMS\Serializer\Annotation\SerializedName('slug')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $slug;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('template_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $templateCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('tone')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $tone;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $type;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $userId;
    
	public function __construct()
	{
		$this->createdAt = "";
		$this->deletedAt = "";
		$this->description = "";
		$this->edit = 0;
		$this->fields = [];
		$this->group = "";
		$this->icon = "";
		$this->id = 0;
		$this->image = "";
		$this->lang = "";
		$this->name = "";
		$this->new = 0;
		$this->package = "";
		$this->professional = 0;
		$this->prompt = "";
		$this->public = 0;
		$this->slug = "";
		$this->status = 0;
		$this->templateCode = "";
		$this->tone = 0;
		$this->type = "";
		$this->updatedAt = "";
		$this->userId = 0;
	}
}
