<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Data13
{
	#[\JMS\Serializer\Annotation\SerializedName('bullet_points')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $bulletPoints;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deletedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('feature_image')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $featureImage;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('tags')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tags;
    
	#[\JMS\Serializer\Annotation\SerializedName('target_audience')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $targetAudience;
    
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $userId;
    
	public function __construct()
	{
		$this->bulletPoints = "";
		$this->deletedAt = "";
		$this->description = "";
		$this->featureImage = "";
		$this->id = 0;
		$this->name = "";
		$this->tags = "";
		$this->targetAudience = "";
		$this->userId = 0;
	}
}
