<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Data10
{
	#[\JMS\Serializer\Annotation\SerializedName('category')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $category;
    
	#[\JMS\Serializer\Annotation\SerializedName('chat_code')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $chatCode;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deletedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('logo')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $logo;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('prompt')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $prompt;
    
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $status;
    
	#[\JMS\Serializer\Annotation\SerializedName('sub_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $subName;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $type;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	public function __construct()
	{
		$this->category = "";
		$this->chatCode = "";
		$this->createdAt = "";
		$this->deletedAt = "";
		$this->description = "";
		$this->id = 0;
		$this->logo = "";
		$this->name = "";
		$this->prompt = "";
		$this->status = 0;
		$this->subName = "";
		$this->type = "";
		$this->updatedAt = "";
	}
}
