<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Data7
{
	#[\JMS\Serializer\Annotation\SerializedName('audio_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $audioType;
    
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('deleted_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $deletedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('description')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $description;
    
	#[\JMS\Serializer\Annotation\SerializedName('expires_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $expiresAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('file_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $fileName;
    
	#[\JMS\Serializer\Annotation\SerializedName('format')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $format;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('length')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $length;
    
	#[\JMS\Serializer\Annotation\SerializedName('plan_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $planType;
    
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $size;
    
	#[\JMS\Serializer\Annotation\SerializedName('storage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $storage;
    
	#[\JMS\Serializer\Annotation\SerializedName('task')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $task;
    
	#[\JMS\Serializer\Annotation\SerializedName('temp_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $tempName;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $title;
    
	#[\JMS\Serializer\Annotation\SerializedName('transcript')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $transcript;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('url')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $url;
    
	#[\JMS\Serializer\Annotation\SerializedName('user_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $userId;
    
	#[\JMS\Serializer\Annotation\SerializedName('words')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $words;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workbook;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_folder_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $workbookFolderId;
    
	#[\JMS\Serializer\Annotation\SerializedName('workbook_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $workbookId;
    
	public function __construct()
	{
		$this->audioType = "";
		$this->createdAt = "";
		$this->deletedAt = "";
		$this->description = "";
		$this->expiresAt = "";
		$this->fileName = "";
		$this->format = "";
		$this->id = 0;
		$this->length = "";
		$this->planType = "";
		$this->size = "";
		$this->storage = "";
		$this->task = "";
		$this->tempName = "";
		$this->title = "";
		$this->transcript = "";
		$this->updatedAt = "";
		$this->url = "";
		$this->userId = 0;
		$this->words = 0;
		$this->workbook = "";
		$this->workbookFolderId = 0;
		$this->workbookId = 0;
	}
}
