<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Pivot
{
	#[\JMS\Serializer\Annotation\SerializedName('model_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $modelId;
    
	#[\JMS\Serializer\Annotation\SerializedName('model_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $modelType;
    
	#[\JMS\Serializer\Annotation\SerializedName('role_id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $roleId;
    
	public function __construct()
	{
		$this->modelId = 0;
		$this->modelType = "";
		$this->roleId = 0;
	}
}
