<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai\Models\Shared;


class Role
{
	#[\JMS\Serializer\Annotation\SerializedName('created_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $createdAt;
    
	#[\JMS\Serializer\Annotation\SerializedName('guard_name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $guardName;
    
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    public int $id;
    
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
	#[\JMS\Serializer\Annotation\SerializedName('pivot')]
    #[\JMS\Serializer\Annotation\Type('taamai\taamai\Models\Shared\RolePivot')]
    public RolePivot $pivot;
    
	#[\JMS\Serializer\Annotation\SerializedName('updated_at')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $updatedAt;
    
	public function __construct()
	{
		$this->createdAt = "";
		$this->guardName = "";
		$this->id = 0;
		$this->name = "";
		$this->pivot = new \taamai\taamai\Models\Shared\RolePivot();
		$this->updatedAt = "";
	}
}
