<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai;

class ChatWithPdf 
{
	
	public const NEW_REQUEST_SERVERS = [
		'https://taam.ai/api',
	];
	
	public const SENDANDGETMSGTOCHATPDF_SERVERS = [
		'https://taam.ai/api',
	];
	
	public const FILEUPLOAD_SERVERS = [
		'https://taam.ai/api',
	];
	
	public const PDFTOTEXT_SERVERS = [
		'https://taam.ai/api',
	];
	
	public const UPLOADFILEFORCHATPDF_SERVERS = [
		'https://taam.ai/api',
	];

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * New Request
     * 
     * @param \taamai\taamai\Models\Operations\NewRequestRequest $request
     * @param string $serverURL
     * @return \taamai\taamai\Models\Operations\NewRequestResponse
     */
	public function newRequest(
        ?\taamai\taamai\Models\Operations\NewRequestRequest $request,
        ?string $serverURL = null,
    ): \taamai\taamai\Models\Operations\NewRequestResponse
    {
        $baseUrl = Utils\Utils::templateUrl(ChatWithPdf::NEW_REQUEST_SERVERS[0], array(
        ));
        if (!empty($serverURL)) {
            $baseUrl = $serverURL;
        }
        
        $url = Utils\Utils::generateUrl($baseUrl, '/pdf/text');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\taamai\taamai\Models\Operations\NewRequestRequest::class, $request, null));
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \taamai\taamai\Models\Operations\NewRequestResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }

        return $response;
    }
	
    /**
     * Send and get msg to chat pdf
     * 
     * @param \taamai\taamai\Models\Operations\SendandgetmsgtochatpdfRequestBody $request
     * @param string $serverURL
     * @return \taamai\taamai\Models\Operations\SendandgetmsgtochatpdfResponse
     */
	public function sendandgetmsgtochatpdf(
        ?\taamai\taamai\Models\Operations\SendandgetmsgtochatpdfRequestBody $request,
        ?string $serverURL = null,
    ): \taamai\taamai\Models\Operations\SendandgetmsgtochatpdfResponse
    {
        $baseUrl = Utils\Utils::templateUrl(ChatWithPdf::SENDANDGETMSGTOCHATPDF_SERVERS[0], array(
        ));
        if (!empty($serverURL)) {
            $baseUrl = $serverURL;
        }
        
        $url = Utils\Utils::generateUrl($baseUrl, '/send-message');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "form");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \taamai\taamai\Models\Operations\SendandgetmsgtochatpdfResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }

        return $response;
    }
	
    /**
     * file upload
     * 
     * @param \taamai\taamai\Models\Operations\FileuploadRequestBody $request
     * @param string $serverURL
     * @return \taamai\taamai\Models\Operations\FileuploadResponse
     */
	public function fileupload(
        ?\taamai\taamai\Models\Operations\FileuploadRequestBody $request,
        ?string $serverURL = null,
    ): \taamai\taamai\Models\Operations\FileuploadResponse
    {
        $baseUrl = Utils\Utils::templateUrl(ChatWithPdf::FILEUPLOAD_SERVERS[0], array(
        ));
        if (!empty($serverURL)) {
            $baseUrl = $serverURL;
        }
        
        $url = Utils\Utils::generateUrl($baseUrl, '/pdf/upload');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "multipart");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \taamai\taamai\Models\Operations\FileuploadResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }

        return $response;
    }
	
    /**
     * pdf to text
     * 
     * @param \taamai\taamai\Models\Operations\PdftotextRequestBody $request
     * @param string $serverURL
     * @return \taamai\taamai\Models\Operations\PdftotextResponse
     */
	public function pdftotext(
        ?\taamai\taamai\Models\Operations\PdftotextRequestBody $request,
        ?string $serverURL = null,
    ): \taamai\taamai\Models\Operations\PdftotextResponse
    {
        $baseUrl = Utils\Utils::templateUrl(ChatWithPdf::PDFTOTEXT_SERVERS[0], array(
        ));
        if (!empty($serverURL)) {
            $baseUrl = $serverURL;
        }
        
        $url = Utils\Utils::generateUrl($baseUrl, '/pdf-text');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "multipart");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \taamai\taamai\Models\Operations\PdftotextResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }

        return $response;
    }
	
    /**
     * upload file for chat pdf
     * 
     * @param \taamai\taamai\Models\Operations\UploadfileforchatpdfRequestBody $request
     * @param string $serverURL
     * @return \taamai\taamai\Models\Operations\UploadfileforchatpdfResponse
     */
	public function uploadfileforchatpdf(
        ?\taamai\taamai\Models\Operations\UploadfileforchatpdfRequestBody $request,
        ?string $serverURL = null,
    ): \taamai\taamai\Models\Operations\UploadfileforchatpdfResponse
    {
        $baseUrl = Utils\Utils::templateUrl(ChatWithPdf::UPLOADFILEFORCHATPDF_SERVERS[0], array(
        ));
        if (!empty($serverURL)) {
            $baseUrl = $serverURL;
        }
        
        $url = Utils\Utils::generateUrl($baseUrl, '/add-url');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "request", "multipart");
        if ($body !== null) {
            $options = array_merge_recursive($options, $body);
        }
        $options['headers']['Accept'] = '*/*';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \taamai\taamai\Models\Operations\UploadfileforchatpdfResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
        }

        return $response;
    }
}