<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace taamai\taamai;

/**
 * Taamai
 * 
 * @package taamai\taamai
 * @access public
 */
class Taamai
{
	public const SERVERS = [
		'https://taam.ai/api',
		'http://127.0.0.1:8000/api',
	];
  	
	public WorkbookAndFolders $workbookAndFolders;
	
	public CustimTemplates $custimTemplates;
	
	public ChatWithPdf $chatWithPdf;
	
	public Misc $misc;
	
	public AddonFeatures $addonFeatures;
	
	public Auth $auth;
	
	public Product $product;
	
	public PromptTemplate $promptTemplate;
	
	public Templates $templates;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return TaamaiBuilder
	 */
	public static function builder(): TaamaiBuilder
	{
		return new TaamaiBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->workbookAndFolders = new WorkbookAndFolders($this->sdkConfiguration);
		
		$this->custimTemplates = new CustimTemplates($this->sdkConfiguration);
		
		$this->chatWithPdf = new ChatWithPdf($this->sdkConfiguration);
		
		$this->misc = new Misc($this->sdkConfiguration);
		
		$this->addonFeatures = new AddonFeatures($this->sdkConfiguration);
		
		$this->auth = new Auth($this->sdkConfiguration);
		
		$this->product = new Product($this->sdkConfiguration);
		
		$this->promptTemplate = new PromptTemplate($this->sdkConfiguration);
		
		$this->templates = new Templates($this->sdkConfiguration);
	}
}